services:
    hexo-blog:
        build: .
        restart: always
        ports:
            - "4000:4000"
        environment:
            VIRTUAL_HOST: tsalon.tech
            VIRTUAL_PORT: 4000
            LETSENCRYPT_HOST: tsalon.tech
            LETSENCRYPT_EMAIL: eyrefree@eyrefree.org
        logging:
            options:
                max-size: "10m"
                max-file: "3"

networks:
  default:
    external: true
    name: nginxproxy